?start: cd_stmt | QUIT_STMT 

cd_stmt: 'CHANGE'i path ';'?
QUIT_STMT: 'QUIT'i ';'?


path: absolute_path | relative_path | path_with_environment_variable


absolute_path: windows_path | linux_path
relative_path: ('.'|'..') ['\\' | '/'] (DIRECTORY ('\\' | '/'))*
path_with_environment_variable: '$' CNAME ('\\' | '/') (DIRECTORY ('\\' | '/'))*



windows_path: LETTER ':\\' [ DIRECTORY '\\' ]*
linux_path: '/' [ DIRECTORY '/' ]*


DATETIME.5: /\d{1,4}-\d{1,4}-\d{1,4}(\s*[\sTt]?\s*\d\d\:\d\d(\:\d\d)?)?/
NUMBER.3: NUMBER
BOOLEAN.2: i"true" | i"false"
STRING.1: ESCAPED_STRING
NULL: "null"

ASTERISK: '*'
PROPERTY: CNAME
DIRECTORY: /[^/\\]*/
VARIABLE_STRING: /(.*)(?=\}\})/ 
WILDCARD_TEXT: /[\][()_\-?*\.\w\s]*\.\w*/ | '*' | '?'
OPERATOR: '=' | '<>' | '!=' | '<' | '>' | '>=' | '<=' | 'FUZZY MATCH' | ['REGEX'] 'MATCH' 

%import common.WS
%import common.LETTER
%import common.CNAME
%import common.ESCAPED_STRING
%import common.NUMBER

%ignore WS
